replicas: 1

# Admin user via env suportado pela imagem legacy do chart
extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin
  - name: KEYCLOAK_FRONTEND_URL
    value: https://keycloak.timedevops.click/auth

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4
  postgresqlUsername: keycloak
  postgresqlPassword: keycloak
  postgresqlDatabase: keycloak

# Vamos deixar o ingress do chart desabilitado e usar o que jรก existe no cluster
ingress:
  enabled: false
