apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-e2e
  namespace: default
  labels:
    app.kubernetes.io/name: hello-world-e2e
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: platform-services
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hello-world-e2e.timedevops.click
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: nginx
  rules:
    - host: hello-world-e2e.timedevops.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-e2e
                port:
                  number: 80
