apiVersion: v1
kind: Service
metadata:
  name: hello-world-e2e
  namespace: default
  labels:
    app.kubernetes.io/name: hello-world-e2e
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: platform-services
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: hello-world-e2e
